# Generated by Django 3.0.5 on 2020-04-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=30)),
                ('postscript', models.TextField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('is_match', models.BooleanField(default=False)),
                ('match_id', models.IntegerField(default=-1)),
                ('add_date', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('口罩', '口罩'), ('防护服', '防护服'), ('护目镜', '护目镜'), ('呼吸机', '呼吸机'), ('血袋', '血袋'), ('药品', '药品')], max_length=50)),
                ('x1', models.PositiveIntegerField()),
                ('x2', models.PositiveIntegerField()),
                ('x3', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': '物资',
                'verbose_name_plural': '物资',
            },
        ),
    ]
