# Generated by Django 3.0.5 on 2020-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=256)),
                ('linkman', models.CharField(max_length=5)),
                ('is_hospital', models.BooleanField(default=True)),
                ('last_login', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
